version: '3.9'
services:
  php:
    build: .
    volumes:
      - ./:/app/
      - ./docker/php-fpm/docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
      - ./docker/php-fpm/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./docker/php-fpm/php.ini-production:/usr/local/etc/php/php.ini-production
    container_name: artfora-php
    restart: on-failure
  web-server:
    container_name: artfora-nginx
    image: nginx:1.20.1
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - /etc/letsencrypt/:/etc/letsencrypt
      - ./:/app/
    ports:
      - 8080:80
    restart: on-failure
    depends_on:
      - php
  db:
    container_name: artfora-pgsql
    image: postgres:15rc2
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./storage/pgsql:/var/lib/postgresql/data
