version: '3.9'
services:
  php:
    build: .
    volumes:
      - ./:/app/
      - ./docker/php-fpm/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./docker/php-fpm/php.ini-production:/usr/local/etc/php/php.ini-production
    container_name: artfora-php
    restart: on-failure
  web-server:
    container_name: artfora-nginx
    image: nginx:1.20.1
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt
      - ./:/home/dev/${CI_PROJECT_NAME}
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - artfora-php
    restart: on-failure
  db:
    container_name: artfora-pgsql
    image: postgres:15-rc2
    environment:
      POSTGRES_USER: artforawebuser
      POSTGRES_PASSWORD: AASDJKHJKASDBNASDKJH12312312313AGSDGHHJKGJHaskdjhasd
      POSTGRES_DB: artfora
    volumes:
      - /var/lib/artfora-pgsql:/var/lib/postgresql/data
